color: null
description: null
fieldLayouts:
  95679384-6c45-457c-b83f-e176d79eaf6e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-29T08:09:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8c98ef47-d18e-4c2b-8b6a-ae2c053463e0 # Tech Item Name
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80a39c06-3583-46e7-a017-0a789f0aadc8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-29T08:09:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ece825c7-5d9b-4ecc-818e-878171b7526c # Tech Item Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 546d58be-37b9-4e0e-a6ec-13dbce5a642a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-19T10:23:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 40863f10-bdae-4ef4-a283-bb9867778f26 # Tech Item in overview
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f51d539d-fa21-4d97-8dd6-e6a1fa2a12b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-29T08:09:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cfd6dc66-37b4-4d63-9fe9-a7ff90dc5847 # Tech Item Category
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef7c4b16-d2d9-4fae-82ba-66192914a2c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-19T07:47:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4af01e02-8b61-4ba9-94b8-ea5308c4fe25 # Tech Item Stack
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94ef21d8-b1e7-4dc7-8e26-91033f1af489
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bca28692-d70c-4a27-80e5-e49b93c28ebf
        userCondition: null
handle: techItem
hasTitleField: false
icon: null
name: 'Tech Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{techItemName} - {techItemCategory} - overview: {techItemInOverview} - {techItemStack}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
