columnSuffix: null
handle: projectLinks
instructions: null
name: 'Project Links'
searchable: false
settings:
  addRowLabel: 'Add a link'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Group
            -
              - handle
              - group
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Url
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - url
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Help Text'
            -
              - handle
              - helpText
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
